version: "3.8"
networks:
  scroll:
    external: true
services:
  web:
    # image: seasun245/scroll_stageus:latest
    build: .
    container_name: scroll
    ports:
      - "3000:3000"
    networks:
      scroll:
        ipv4_address: 192.168.160.2
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # restart: always
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/postgres/data:/var/lib/postgresql/data
    networks:
      scroll:
        ipv4_address: 192.168.160.3
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: "27017"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "1234"
      MONGO_INITDB_DATABASE: mongoLog
      MONGO_URI: mongodb://mongodb-myapp:27017/log
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodb/data:/data/db
    networks:
      scroll:
        ipv4_address: 192.168.160.4
    user: postgres
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:7.17.0
  #   ports:
  #    - 9200:9200
  #   networks:
  #    - default
  #   volumes:
  #    - /home/ubuntu/elastic/data:/usr/share/elasticsearch/data
  #   environment:
  #     # cluster.name: docker-cluster
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: -Xms512m -Xmx512m
  #     TZ: Asia/Seoul
  #     # TAKE_FILE_OWNERSHIP: "true"
  #     # http.host: 0.0.0.0
  #     # http.port: 9200
  #     # http.cors.enabled: "true"
  #     # http.cors.allow-credentials: "true"
  #     # http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
  #     # http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
  #   networks:
  #     scroll:
  #       ipv4_address: 192.168.160.5
  #   restart: always
  #   # user: root
  #   # restart: always
  #   # privileged: true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1